### ISSUE TITLE
最新の Web Audio API に近づけてほしい

### ISSUE THREAD

**Issue by petamoriken** [g200kg/WAAPISim#8]
playbackState がなくなるなど、若干 Web Audio API の仕様が変わってきていると思います。
是非、WAAPISim での polyfill 対応を新しくしてほしいと思います。

**Comment by g200kg** [comment]
時間があれば新しい仕様に合わせたいと思いますが、基本的にはFirefoxでのネイティブのWebAudioAPIの実装が進み、IEもWebAudioAPIへの対応を発表していますので、もう役目を終えつつあるかと思ってはいます。
